//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardAdminFS_2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int id { get; set; }
        public string head { get; set; }
        public string th1 { get; set; }
        public string th2 { get; set; }
        public string img { get; set; }
        public string destino { get; set; }
        public string tipo { get; set; }
        public string oculto { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    }
}
