//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardAdminFS_2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeInfoFinanciera
    {
        public int id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime lastupdate { get; set; }
        public string id_userCreated { get; set; }
        public string tipo { get; set; }
        public string path { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
    }
}
