//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardAdminFS_2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCarrouselItems
    {
        public int id { get; set; }
        public string img { get; set; }
        public string h2tag { get; set; }
        public string ptag { get; set; }
        public string id_userCreated { get; set; }
    }
}
