//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardAdminFS_2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeProductosFinancieros
    {
        public int id { get; set; }
        public string title { get; set; }
        public string descripcion { get; set; }
        public string montoCredito { get; set; }
        public Nullable<int> plazoMinimo { get; set; }
        public int plazoMaximo { get; set; }
        public string frecuenciasDePago { get; set; }
        public string esquemaDeCobro { get; set; }
        public string requisitos { get; set; }
        public string tasaDeInteres { get; set; }
        public string CAT { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public string id_userCreated { get; set; }
        public string img { get; set; }
        public string tipocredito { get; set; }
        public string tencologiaCrediticia { get; set; }
        public Nullable<int> lapMaxSemanas { get; set; }
        public Nullable<int> lapMinSemanas { get; set; }
        public string tipoRetornoPagoSemanal { get; set; }
        public string tipoRetornoPagoCatorcenal { get; set; }
        public string tipoRetornoPago28Dias { get; set; }
        public string otrasComisones { get; set; }
        public Nullable<int> numeroDeIntegrantes { get; set; }
        public string grantiaPersonalAval { get; set; }
        public string edad { get; set; }
        public string soloclientes { get; set; }
        public string costoTotalAnualCredito { get; set; }
    }
}
