//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardAdminFS_2.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEnt : DbContext
    {
        public DBEnt()
            : base("name=DBEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdminBitacora> AdminBitacora { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<HomeAnuncioCookies> HomeAnuncioCookies { get; set; }
        public virtual DbSet<HomeBarras> HomeBarras { get; set; }
        public virtual DbSet<HomeBeneficios> HomeBeneficios { get; set; }
        public virtual DbSet<HomeCarrouselItems> HomeCarrouselItems { get; set; }
        public virtual DbSet<HomeCodigoDeEtica> HomeCodigoDeEtica { get; set; }
        public virtual DbSet<HomeContactoDatos> HomeContactoDatos { get; set; }
        public virtual DbSet<HomeCostosComisiones> HomeCostosComisiones { get; set; }
        public virtual DbSet<HomeCounters> HomeCounters { get; set; }
        public virtual DbSet<HomeDatosExtra> HomeDatosExtra { get; set; }
        public virtual DbSet<HomeInfoFinanciera> HomeInfoFinanciera { get; set; }
        public virtual DbSet<HomeMision> HomeMision { get; set; }
        public virtual DbSet<HomeProductosFinancieros> HomeProductosFinancieros { get; set; }
        public virtual DbSet<HomePromociones> HomePromociones { get; set; }
        public virtual DbSet<HomeSucursales> HomeSucursales { get; set; }
        public virtual DbSet<HomeUNE> HomeUNE { get; set; }
        public virtual DbSet<HomeValores> HomeValores { get; set; }
        public virtual DbSet<HomeVideoCategorias> HomeVideoCategorias { get; set; }
        public virtual DbSet<HomeVideoITems> HomeVideoITems { get; set; }
        public virtual DbSet<HomeVision> HomeVision { get; set; }
        public virtual DbSet<ProductoFinancieroInteres> ProductoFinancieroInteres { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestingT> TestingT { get; set; }
    }
}
